---

- name: Add Docker apt key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  become: true
  ansible.builtin.apt_repository:
    # yamllint disable-line
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ docker_packages }}"

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true

- name: Reset connection so docker group is picked up.
  ansible.builtin.meta: reset_connection

...
