---

- name: "Install python-pip package"
  become: true
  apt:
    name: python3-pip
    state: present
    update_cache: true

- name: "Install docker-compose with pip"
  pip:
    name: docker-compose
    version: "{{ docker_compose_version }}"
    state: present

...
