---

- name: Install prerequisites
  become: true
  ansible.builtin.apt:
    name: "python3-requests"
    update_cache: true

- name: Create networks
  community.docker.docker_network:
    name: "{{ item }}"
  loop: "{{ docker_networks }}"
