---

- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
    update_cache: true

- name: Install python packages
  ansible.builtin.pip:
    name: "requests"
    extra_args: --user

- name: Create networks
  community.docker.docker_network:
    name: "{{ item }}"
  loop: "{{ docker_networks }}"
  when: docker_networks is defined
