---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    virtualbox
platforms:
  - name: instance
    box: ubuntu/jammy64
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: ../tests
